[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.http_server]
command = "cargo"
args = ["run", "--bin", "http_server"]

[tasks.grpc_server]
command = "cargo"
args = ["run", "--bin", "grpc_server"]

[tasks.run]
dependencies = [
    "http_server",
    "grpc_server"
]
