error_on_line_overflow = true
error_on_unformatted = true
indent_style = "Block"
brace_style = "PreferSameLine"
chain_width = 70
wrap_comments = true
comment_width = 70
condense_wildcard_suffixes = true
fn_params_layout = "Compressed"
fn_call_width = 70
fn_single_line = true
force_multiline_blocks = true
hard_tabs = true
imports_layout = "Vertical"
imports_granularity = "Crate"
reorder_imports = true
group_imports = "StdExternalCrate"
reorder_impl_items = true
reorder_modules = true